# Generated by Django 5.2 on 2025-04-21 10:17

import home.utils
import image_compare.storage_backends
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uniformChecker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(storage=image_compare.storage_backends.PrivateMediaStorage, upload_to=home.utils.get_uniform_checker_image)),
                ('result', models.BooleanField()),
                ('confidence', models.FloatField()),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
