# Generated by Django 5.2 on 2025-04-30 08:17

import django.db.models.deletion
import home.utils
import image_compare.storage_backends
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uniformChecker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(storage=image_compare.storage_backends.PrivateMediaStorage, upload_to=home.utils.get_uniform_checker_image)),
                ('result', models.BooleanField()),
                ('confidence', models.FloatField()),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(storage=image_compare.storage_backends.MediaStorage, upload_to=home.utils.get_clip_data_set)),
                ('prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='home_datase_created_42990f_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrainingState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_trained_time', models.DateTimeField(blank=True, null=True)),
                ('last_trained_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.dataset')),
            ],
        ),
    ]
